import { spawn } from "node:child_process";
import { rm, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { env } from "@/lib/env";
import type { Persona } from "@/lib/types";

export function applySpokenPronunciations(script: string) {
  return script.replace(/\bASCO\b/g, "Ask-oh").replace(/\bASKO\b/g, "Ask-oh");
}

function runProcess(command: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: "pipe" });
    let stderr = "";
    child.stderr?.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(
          new Error(
            `${path.basename(command)} exited with code ${code}: ${stderr.slice(0, 300)}`
          )
        );
      }
    });
  });
}

export async function synthesizeSpeech({
  script,
  persona
}: {
  script: string;
  persona: Persona;
}) {
  const voiceName = process.env[persona.voiceEnvKey];
  if (!voiceName) {
    return {
      provider: "skipped",
      audioPath: null,
      note: `TTS skipped — set ${persona.voiceEnvKey} to a Kokoro voice ID (e.g. am_fenrir).`
    };
  }

  const processedScript = applySpokenPronunciations(script);

  // HTTP mode — if VOICE_API_URL is set, call a hosted Kokoro FastAPI endpoint
  if (env.VOICE_API_URL) {
    const response = await fetch(`${env.VOICE_API_URL}/v1/audio/speech`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "kokoro",
        input: processedScript,
        voice: voiceName,
        response_format: "mp3"
      })
    });
    if (!response.ok) {
      throw new Error(`Kokoro TTS failed: ${response.status} ${await response.text()}`);
    }
    return {
      provider: "kokoro-http",
      audioBuffer: Buffer.from(await response.arrayBuffer()),
      note: "Audio generated by Kokoro (HTTP)."
    };
  }

  // Local Python mode — spawn scripts/generate-kokoro-dj-voice.py directly.
  // Requires: pip install kokoro numpy soundfile
  // Voice IDs: am_fenrir, af_heart, af_bella, am_michael, bm_lewis, af_sarah, am_echo, am_adam
  const tempId = `kokoro-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const tempWav = path.join(tmpdir(), `${tempId}.wav`);
  const tempMp3 = path.join(tmpdir(), `${tempId}.mp3`);
  const pyScript = path.resolve("scripts/generate-kokoro-dj-voice.py");
  const ffmpeg = process.env.FFMPEG_PATH ?? "ffmpeg";

  // KOKORO_PYTHON_CMD overrides auto-detection.
  // Default: "py -3.12" on Windows, "python3" on Linux/macOS.
  const rawPyCmd = process.env.KOKORO_PYTHON_CMD;
  const [pyCmd, ...pyPrefix] = rawPyCmd
    ? rawPyCmd.split(/\s+/)
    : process.platform === "win32"
      ? ["py", "-3.12"]
      : ["python3"];

  try {
    await runProcess(pyCmd, [
      ...pyPrefix,
      pyScript,
      "--mode",
      "stinger",
      "--voice",
      voiceName,
      "--output",
      tempWav,
      "--text",
      processedScript
    ]);

    // Convert WAV → MP3 with FFmpeg
    await runProcess(ffmpeg, [
      "-y",
      "-i",
      tempWav,
      "-c:a",
      "libmp3lame",
      "-b:a",
      "128k",
      tempMp3
    ]);

    const audioBuffer = await readFile(tempMp3);
    return {
      provider: "kokoro-local",
      audioBuffer,
      note: "Audio generated by local Kokoro Python library."
    };
  } finally {
    await Promise.all([
      rm(tempWav, { force: true }).catch(() => {}),
      rm(tempMp3, { force: true }).catch(() => {})
    ]);
  }
}
